import "./globals.css";
import { Lato } from "next/font/google";
import StyledComponentsRegistry from "../lib/registry";
import Header from "components/Header";

// const inter = Inter({ subsets: ["latin"] });
const lato = Lato({
  weight: ["100", "400", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        <StyledComponentsRegistry>
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
